export const initialCafeSettings = {
  cafeName: "Petuk Adda Cafe",
  tagline: "Where every sip and bite tells a story.",
  logo: "https://reactheme.com/products/wordpress/dinenos/wp-content/uploads/2023/02/dineos-logo-white.svg",
  address: "Salboni, Sakadihi-Ailakundi Road, Near Salboni High School, Salboni, West Bengal 722102",
  phone: "+91 9932148058",
  altPhone: "+91 6292314286",
  email: "petukaddacafe@gmail.com",
  website: "https://petukaddacafe.com",
  currency: "₹",
  currencyCode: "INR",
  taxRate: 5.0, // 5% GST
  taxNumber: "GSTIN-19AABCU9603R1ZM",
  serviceChargeRate: 0.0,
  loyaltyPointsPerHundred: 1, // 1 point per 100 spent
  loyaltyPointRedemptionValue: 1, // 1 point = 1 currency unit
  minPointsToRedeem: 50,
  invoicePrefix: "PAC-",
  invoiceFooterMessage: "Thank you for visiting Petuk Adda Cafe! Where every sip and bite tells a story.",
  enableCouponStacking: false,
  autoPrintReceipt: true,
  openingHours: "Morning: 09:00 AM – 01:30 PM | Evening: 04:30 PM – 10:30 PM (Open All Days)",
  deliveryArea: "Bankura Town",
  lowStockThresholdDefault: 5
};

export const initialCategories = [
  { id: "cat-beverage", name: "Beverage", slug: "beverage", icon: "CupSoda", color: "#3B82F6", itemCount: 10, isActive: true },
  { id: "cat-breakfast", name: "Break Fast", slug: "break-fast", icon: "Croissant", color: "#F59E0B", itemCount: 3, isActive: true },
  { id: "cat-moglai", name: "Moglai", slug: "moglai", icon: "Sparkles", color: "#D97706", itemCount: 3, isActive: true },
  { id: "cat-chowmin-rolls-pasta", name: "Chowmin, Rolls & Pasta", slug: "chowmin-rolls-pasta", icon: "Utensils", color: "#EF4444", itemCount: 14, isActive: true },
  { id: "cat-soup", name: "Soup", slug: "soup", icon: "Soup", color: "#EA580C", itemCount: 2, isActive: true },
  { id: "cat-noodles", name: "Noodles", slug: "noodles", icon: "UtensilsCrossed", color: "#E11D48", itemCount: 2, isActive: true },
  { id: "cat-starter-veg", name: "Starter (Veg)", slug: "starter-veg", icon: "Leaf", color: "#10B981", itemCount: 7, isActive: true },
  { id: "cat-starter-nonveg", name: "Starter (Non Veg)", slug: "starter-nonveg", icon: "Flame", color: "#DC2626", itemCount: 6, isActive: true },
  { id: "cat-chinese-gravy", name: "Chinese Gravy", slug: "chinese-gravy", icon: "BowlFood", color: "#B45309", itemCount: 5, isActive: true },
  { id: "cat-indian-gravy", name: "Indian Gravy", slug: "indian-gravy", icon: "CookingPot", color: "#DD5903", itemCount: 15, isActive: true },
  { id: "cat-roti", name: "Roti", slug: "roti", icon: "CircleDot", color: "#78350F", itemCount: 6, isActive: true },
  { id: "cat-rice", name: "Rice", slug: "rice", icon: "Utensils", color: "#059669", itemCount: 7, isActive: true },
  { id: "cat-mocktail", name: "Mocktail", slug: "mocktail", icon: "GlassWater", color: "#0284C7", itemCount: 4, isActive: true },
  { id: "cat-shake", name: "Shake", slug: "shake", icon: "Milk", color: "#DB2777", itemCount: 4, isActive: true },
  { id: "cat-ice-cream", name: "Ice Cream", slug: "ice-cream", icon: "IceCream", color: "#9333EA", itemCount: 3, isActive: true },
  { id: "cat-lassi", name: "Lassi", slug: "lassi", icon: "GlassWater", color: "#16A34A", itemCount: 3, isActive: true },
  // ---- Production hardening pack: mission categories (Coffee / Cold Brews / Teas / Bakery) ----
  { id: "cat-coffee", name: "Coffee", slug: "coffee", icon: "Coffee", color: "#6F4E37", itemCount: 3, isActive: true },
  { id: "cat-cold-brews", name: "Cold Brews", slug: "cold-brews", icon: "CupSoda", color: "#0EA5E9", itemCount: 3, isActive: true },
  { id: "cat-teas", name: "Teas", slug: "teas", icon: "Leaf", color: "#15803D", itemCount: 3, isActive: true },
  { id: "cat-bakery", name: "Bakery", slug: "bakery", icon: "Croissant", color: "#D97706", itemCount: 3, isActive: true }
];

export const initialAddons = [
  { id: "add-1", name: "Extra Cheese / Butter", price: 20, category: "Topping", isAvailable: true },
  { id: "add-2", name: "Extra Egg", price: 15, category: "Food", isAvailable: true },
  { id: "add-3", name: "Extra Chicken Pieces", price: 40, category: "Food", isAvailable: true },
  { id: "add-4", name: "Green Salad & Sauce Dip", price: 20, category: "Side", isAvailable: true }
];

export const initialProducts = [
  // ================= 1. BEVERAGE (Page 2) =================
  {
    id: "bev-1",
    name: "Mineral Water",
    category: "cat-beverage",
    categoryId: "cat-beverage",
    categoryName: "Beverage",
    description: "Chilled pure packaged mineral drinking water.",
    costPrice: 6,
    sellingPrice: 10,
    price: 10,
    isVeg: true,
    prepTimeMinutes: 1,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=60",
    variants: [
      { id: "var-bw-1", name: "500ml (₹10)", priceDelta: 0, isDefault: true },
      { id: "var-bw-2", name: "1 Litre (₹20)", priceDelta: 10, isDefault: false },
      { id: "var-bw-3", name: "2 Litre / Pack (₹30)", priceDelta: 20, isDefault: false }
    ],
    allowedAddons: []
  },
  {
    id: "bev-2",
    name: "Tea",
    category: "cat-beverage",
    categoryId: "cat-beverage",
    categoryName: "Beverage",
    description: "Freshly brewed hot aromatic milk chai with traditional Indian spices.",
    costPrice: 4,
    sellingPrice: 10,
    price: 10,
    isVeg: true,
    prepTimeMinutes: 3,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-tea-1", name: "Standard Cup", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "bev-3",
    name: "Green Tea",
    category: "cat-beverage",
    categoryId: "cat-beverage",
    categoryName: "Beverage",
    description: "Refreshing antioxidant-rich hot green tea.",
    costPrice: 6,
    sellingPrice: 20,
    price: 20,
    isVeg: true,
    prepTimeMinutes: 3,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-gt-1", name: "Standard Cup", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "bev-4",
    name: "Coffee",
    category: "cat-beverage",
    categoryId: "cat-beverage",
    categoryName: "Beverage",
    description: "Classic hot milk coffee brewed rich and smooth.",
    costPrice: 7,
    sellingPrice: 20,
    price: 20,
    isVeg: true,
    prepTimeMinutes: 3,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cof-1", name: "Standard Cup", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "bev-5",
    name: "Black Coffee",
    category: "cat-beverage",
    categoryId: "cat-beverage",
    categoryName: "Beverage",
    description: "Strong and robust fresh black coffee.",
    costPrice: 5,
    sellingPrice: 20,
    price: 20,
    isVeg: true,
    prepTimeMinutes: 2,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-bc-1", name: "Standard Cup", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "bev-6",
    name: "Cappuccino",
    category: "cat-beverage",
    categoryId: "cat-beverage",
    categoryName: "Beverage",
    description: "Espresso with velvety steamed milk and frothy foam.",
    costPrice: 18,
    sellingPrice: 50,
    price: 50,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1534778101976-62847782c213?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cap-1", name: "Standard Mug", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "bev-7",
    name: "Cold Coffee",
    category: "cat-beverage",
    categoryId: "cat-beverage",
    categoryName: "Beverage",
    description: "Chilled blended thick creamy cold coffee.",
    costPrice: 25,
    sellingPrice: 70,
    price: 70,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cc-1", name: "Tall Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "bev-8",
    name: "Cold Drink",
    category: "cat-beverage",
    categoryId: "cat-beverage",
    categoryName: "Beverage",
    description: "Chilled carbonated soft drink.",
    costPrice: 12,
    sellingPrice: 20,
    price: 20,
    isVeg: true,
    prepTimeMinutes: 1,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cd-1", name: "Glass / Bottle", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "bev-9",
    name: "Masala Cold Drink",
    category: "cat-beverage",
    categoryId: "cat-beverage",
    categoryName: "Beverage",
    description: "Refreshing cold drink blended with spicy chatpata masala & lemon.",
    costPrice: 14,
    sellingPrice: 30,
    price: 30,
    isVeg: true,
    prepTimeMinutes: 2,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-mcd-1", name: "Standard Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "bev-10",
    name: "Fresh Lime Soda",
    category: "cat-beverage",
    categoryId: "cat-beverage",
    categoryName: "Beverage",
    description: "Crisp sparkling soda with fresh squeezed lime juice (Sweet / Salted / Mix).",
    costPrice: 15,
    sellingPrice: 40,
    price: 40,
    isVeg: true,
    prepTimeMinutes: 3,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-fls-1", name: "Standard Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },

  // ================= 2. BREAK FAST (Page 2) =================
  {
    id: "bf-1",
    name: "Chola Bhatora (2pcs)",
    category: "cat-breakfast",
    categoryId: "cat-breakfast",
    categoryName: "Break Fast",
    description: "Fluffy puffed bhature (2 pcs) served with flavourful spiced chole curry.",
    costPrice: 8,
    sellingPrice: 20,
    price: 20,
    isVeg: true,
    prepTimeMinutes: 6,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cb-1", name: "2 Pcs Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "bf-2",
    name: "Alu Paratha (1pcs)",
    category: "cat-breakfast",
    categoryId: "cat-breakfast",
    categoryName: "Break Fast",
    description: "Golden tawa paratha stuffed with spiced mashed potato filling (1 pc).",
    costPrice: 10,
    sellingPrice: 30,
    price: 30,
    isVeg: true,
    prepTimeMinutes: 5,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ap-1", name: "1 Pc", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "bf-3",
    name: "Egg Toast",
    category: "cat-breakfast",
    categoryId: "cat-breakfast",
    categoryName: "Break Fast",
    description: "Crispy toasted bread coated with pan-fried seasoned eggs.",
    costPrice: 12,
    sellingPrice: 30,
    price: 30,
    isVeg: false,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-et-1", name: "Standard Portion", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },

  // ================= 3. MOGLAI (Page 2) =================
  {
    id: "mog-1",
    name: "Moglai Paratha",
    category: "cat-moglai",
    categoryId: "cat-moglai",
    categoryName: "Moglai",
    description: "Crispy golden deep-fried flaky pastry filled with egg and special spices.",
    costPrice: 25,
    sellingPrice: 60,
    price: 60,
    isVeg: false,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-mp-1", name: "Standard", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "mog-2",
    name: "Chicken Moglai Paratha",
    category: "cat-moglai",
    categoryId: "cat-moglai",
    categoryName: "Moglai",
    description: "Stuffed crispy moglai paratha loaded with minced spiced chicken and egg.",
    costPrice: 40,
    sellingPrice: 90,
    price: 90,
    isVeg: false,
    prepTimeMinutes: 10,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cmp-1", name: "Standard", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "mog-3",
    name: "Peটুক আdda Special Moglai",
    category: "cat-moglai",
    categoryId: "cat-moglai",
    categoryName: "Moglai",
    description: "Chef's signature jumbo moglai loaded with double chicken, egg & secret spices.",
    costPrice: 55,
    sellingPrice: 120,
    price: 120,
    isVeg: false,
    prepTimeMinutes: 12,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-pasm-1", name: "Special Jumbo", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },

  // ================= 4. CHOWMIN, ROLLS & PASTA (Page 3) =================
  {
    id: "crp-1",
    name: "Veg Chowmin",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Wok-tossed noodles with crunchy fresh seasonal vegetables and soy sauce.",
    costPrice: 15,
    sellingPrice: 40,
    price: 40,
    isVeg: true,
    prepTimeMinutes: 7,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-vc-1", name: "Standard Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "crp-2",
    name: "Egg Chowmin",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Stir-fried noodles tossed with scrambled egg and crisp vegetables.",
    costPrice: 20,
    sellingPrice: 50,
    price: 50,
    isVeg: false,
    prepTimeMinutes: 7,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ec-1", name: "Standard Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-2"]
  },
  {
    id: "crp-3",
    name: "Chicken Chowmin",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Stir-fried noodles tossed with succulent chicken pieces and spices.",
    costPrice: 25,
    sellingPrice: 60,
    price: 60,
    isVeg: false,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cc-1", name: "Standard Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-3"]
  },
  {
    id: "crp-4",
    name: "Egg Chicken Chowmin",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Classic stir-fried noodles tossed with chicken and scrambled egg.",
    costPrice: 30,
    sellingPrice: 70,
    price: 70,
    isVeg: false,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ecc-1", name: "Standard Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-2", "add-3"]
  },
  {
    id: "crp-5",
    name: "Mix Chowmin",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Special mixed noodles tossed with egg, chicken and assorted fresh vegetables.",
    costPrice: 35,
    sellingPrice: 80,
    price: 80,
    isVeg: false,
    prepTimeMinutes: 9,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-mc-1", name: "Standard Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1", "add-3"]
  },
  {
    id: "crp-6",
    name: "Egg Roll",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Flaky paratha rolled with seasoned egg, sliced onions, lime juice and sauces.",
    costPrice: 12,
    sellingPrice: 30,
    price: 30,
    isVeg: false,
    prepTimeMinutes: 5,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-er-1", name: "1 Roll", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1", "add-2"]
  },
  {
    id: "crp-7",
    name: "Egg Chicken Roll",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Flaky paratha layered with egg and wrapped around juicy spiced chicken chunks.",
    costPrice: 28,
    sellingPrice: 60,
    price: 60,
    isVeg: false,
    prepTimeMinutes: 6,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ecr-1", name: "1 Roll", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1", "add-3"]
  },
  {
    id: "crp-8",
    name: "Panner Roll",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Flaky roll stuffed with spiced marinated paneer cubes and crunchy veggies.",
    costPrice: 22,
    sellingPrice: 50,
    price: 50,
    isVeg: true,
    prepTimeMinutes: 6,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-pr-1", name: "1 Roll", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "crp-9",
    name: "Peটুক আdda Special Roll",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "House special jumbo roll loaded with chicken, egg, paneer, and chef's sauce.",
    costPrice: 38,
    sellingPrice: 80,
    price: 80,
    isVeg: false,
    prepTimeMinutes: 7,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-psr-1", name: "1 Jumbo Roll", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "crp-10",
    name: "Veg Pasta",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Penne pasta tossed in flavourful tomato-herb sauce with crunchy veggies.",
    costPrice: 16,
    sellingPrice: 40,
    price: 40,
    isVeg: true,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d628169e?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-vp-1", name: "Standard Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "crp-11",
    name: "Egg Pasta",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Pasta tossed with scrambled eggs, herbs and savoury seasoning.",
    costPrice: 20,
    sellingPrice: 50,
    price: 50,
    isVeg: false,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d628169e?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ep-1", name: "Standard Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1", "add-2"]
  },
  {
    id: "crp-12",
    name: "Chicken Pasta",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Pasta cooked with tender seasoned chicken chunks in rich red sauce.",
    costPrice: 26,
    sellingPrice: 60,
    price: 60,
    isVeg: false,
    prepTimeMinutes: 9,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d628169e?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cp-1", name: "Standard Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1", "add-3"]
  },
  {
    id: "crp-13",
    name: "Egg Chicken Pasta",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Pasta tossed with both seasoned chicken pieces and scrambled egg.",
    costPrice: 32,
    sellingPrice: 70,
    price: 70,
    isVeg: false,
    prepTimeMinutes: 9,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d628169e?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ecp-1", name: "Standard Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1", "add-3"]
  },
  {
    id: "crp-14",
    name: "Mix Pasta",
    category: "cat-chowmin-rolls-pasta",
    categoryId: "cat-chowmin-rolls-pasta",
    categoryName: "Chowmin, Rolls & Pasta",
    description: "Delicious fusion pasta loaded with chicken, egg and assorted vegetables.",
    costPrice: 36,
    sellingPrice: 80,
    price: 80,
    isVeg: false,
    prepTimeMinutes: 10,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d628169e?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-mpast-1", name: "Standard Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1", "add-3"]
  },

  // ================= 5. SOUP (Page 3) =================
  {
    id: "soup-1",
    name: "Hot & Sour Soup(Veg)",
    category: "cat-soup",
    categoryId: "cat-soup",
    categoryName: "Soup",
    description: "Tangy and spicy thick vegetable soup with oriental seasonings.",
    costPrice: 28,
    sellingPrice: 70,
    price: 70,
    isVeg: true,
    prepTimeMinutes: 7,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-hsv-1", name: "1 Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "soup-2",
    name: "Hot & Sour Soup(Chicken)",
    category: "cat-soup",
    categoryId: "cat-soup",
    categoryName: "Soup",
    description: "Spicy and tangy chicken broth loaded with shredded chicken and egg drops.",
    costPrice: 38,
    sellingPrice: 90,
    price: 90,
    isVeg: false,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-hsc-1", name: "1 Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },

  // ================= 6. NOODLES (Page 3) =================
  {
    id: "nood-1",
    name: "Veg Hakka Noodles",
    category: "cat-noodles",
    categoryId: "cat-noodles",
    categoryName: "Noodles",
    description: "Authentic Chinese style wok-tossed Hakka noodles with julienned vegetables.",
    costPrice: 40,
    sellingPrice: 100,
    price: 100,
    isVeg: true,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-vhn-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "nood-2",
    name: "Chicken Hakka Noodles",
    category: "cat-noodles",
    categoryId: "cat-noodles",
    categoryName: "Noodles",
    description: "Wok-tossed Hakka noodles with juicy boneless chicken and crisp veggies.",
    costPrice: 55,
    sellingPrice: 130,
    price: 130,
    isVeg: false,
    prepTimeMinutes: 9,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-chn-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-3"]
  },

  // ================= 7. STARTER(VEG) (Page 3) =================
  {
    id: "stv-1",
    name: "Classic French Fry",
    category: "cat-starter-veg",
    categoryId: "cat-starter-veg",
    categoryName: "Starter (Veg)",
    description: "Crispy golden salted potato fries served with dip.",
    costPrice: 25,
    sellingPrice: 70,
    price: 70,
    isVeg: true,
    prepTimeMinutes: 6,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cff-1", name: "Standard Portion", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "stv-2",
    name: "Masala French Fry",
    category: "cat-starter-veg",
    categoryId: "cat-starter-veg",
    categoryName: "Starter (Veg)",
    description: "Crispy golden french fries tossed in spicy peri-peri chatpata masala.",
    costPrice: 28,
    sellingPrice: 80,
    price: 80,
    isVeg: true,
    prepTimeMinutes: 6,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-mff-1", name: "Standard Portion", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "stv-3",
    name: "Paneer Pokora(4Pcs/8Pcs)",
    category: "cat-starter-veg",
    categoryId: "cat-starter-veg",
    categoryName: "Starter (Veg)",
    description: "Crispy golden batter-fried soft paneer pakoras served with chutney.",
    costPrice: 35,
    sellingPrice: 90,
    price: 90,
    isVeg: true,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    variants: [
      { id: "var-pp-4", name: "4 Pcs (₹90)", priceDelta: 0, isDefault: true },
      { id: "var-pp-8", name: "8 Pcs (₹160)", priceDelta: 70, isDefault: false }
    ],
    allowedAddons: []
  },
  {
    id: "stv-4",
    name: "Paneer 65",
    category: "cat-starter-veg",
    categoryId: "cat-starter-veg",
    categoryName: "Starter (Veg)",
    description: "South-Indian inspired spicy deep-fried paneer cubes tempered with curry leaves.",
    costPrice: 75,
    sellingPrice: 190,
    price: 190,
    isVeg: true,
    prepTimeMinutes: 10,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-p65-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "stv-5",
    name: "Dry Chilli Paneer (8 Pcs)",
    category: "cat-starter-veg",
    categoryId: "cat-starter-veg",
    categoryName: "Starter (Veg)",
    description: "Wok-tossed crisp paneer cubes (8 pcs) in chilli-garlic soya glaze.",
    costPrice: 80,
    sellingPrice: 190,
    price: 190,
    isVeg: true,
    prepTimeMinutes: 10,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-dcp-1", name: "8 Pcs Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "stv-6",
    name: "Crispy Chilli Babycorn",
    category: "cat-starter-veg",
    categoryId: "cat-starter-veg",
    categoryName: "Starter (Veg)",
    description: "Crunchy batter-fried babycorn tossed with peppers, garlic and chilli sauce.",
    costPrice: 70,
    sellingPrice: 180,
    price: 180,
    isVeg: true,
    prepTimeMinutes: 9,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ccb-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "stv-7",
    name: "Dry Chilli Mushroom",
    category: "cat-starter-veg",
    categoryId: "cat-starter-veg",
    categoryName: "Starter (Veg)",
    description: "Crispy button mushrooms tossed in hot garlic chilli seasoning and spring onions.",
    costPrice: 85,
    sellingPrice: 200,
    price: 200,
    isVeg: true,
    prepTimeMinutes: 10,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-dcm-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },

  // ================= 8. STARTER(NON VEG) (Page 4) =================
  {
    id: "stnv-1",
    name: "Chicken Cutlet (1 Pcs)",
    category: "cat-starter-nonveg",
    categoryId: "cat-starter-nonveg",
    categoryName: "Starter (Non Veg)",
    description: "Crispy breadcrumb-coated seasoned minced chicken cutlet (1 pc).",
    costPrice: 15,
    sellingPrice: 35,
    price: 35,
    isVeg: false,
    prepTimeMinutes: 6,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ccut-1", name: "1 Pc", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "stnv-2",
    name: "Chicken 65",
    category: "cat-starter-nonveg",
    categoryId: "cat-starter-nonveg",
    categoryName: "Starter (Non Veg)",
    description: "Spicy and tangy deep-fried chicken chunks tempered with curry leaves & green chillies.",
    costPrice: 70,
    sellingPrice: 180,
    price: 180,
    isVeg: false,
    prepTimeMinutes: 10,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-c65-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "stnv-3",
    name: "Chicken Lolipop(4Pcs)",
    category: "cat-starter-nonveg",
    categoryId: "cat-starter-nonveg",
    categoryName: "Starter (Non Veg)",
    description: "Crispy frenched chicken winglets (4 pcs) coated in spicy Indo-Chinese batter.",
    costPrice: 60,
    sellingPrice: 150,
    price: 150,
    isVeg: false,
    prepTimeMinutes: 10,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cl-1", name: "4 Pcs Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "stnv-4",
    name: "Dragon Chicken",
    category: "cat-starter-nonveg",
    categoryId: "cat-starter-nonveg",
    categoryName: "Starter (Non Veg)",
    description: "Crispy shredded chicken strips tossed in fiery dragon red sauce and cashews.",
    costPrice: 75,
    sellingPrice: 180,
    price: 180,
    isVeg: false,
    prepTimeMinutes: 10,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-dc-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "stnv-5",
    name: "Dry Chilli Chicken",
    category: "cat-starter-nonveg",
    categoryId: "cat-starter-nonveg",
    categoryName: "Starter (Non Veg)",
    description: "Wok-tossed crispy boneless chicken chunks with green chillies, capsicum and soya.",
    costPrice: 80,
    sellingPrice: 190,
    price: 190,
    isVeg: false,
    prepTimeMinutes: 10,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-dcc-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "stnv-6",
    name: "Peটুক আdda Special Chicken Pokoda (4Pcs/8Pcs)",
    category: "cat-starter-nonveg",
    categoryId: "cat-starter-nonveg",
    categoryName: "Starter (Non Veg)",
    description: "Signature spiced crunchy chicken fritters served piping hot with chutney.",
    costPrice: 30,
    sellingPrice: 70,
    price: 70,
    isVeg: false,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=500&auto=format&fit=crop&q=60",
    variants: [
      { id: "var-cpk-4", name: "4 Pcs (₹70)", priceDelta: 0, isDefault: true },
      { id: "var-cpk-8", name: "8 Pcs (₹120)", priceDelta: 50, isDefault: false }
    ],
    allowedAddons: []
  },

  // ================= 9. CHINESE GRAVY (Page 4) =================
  {
    id: "cg-1",
    name: "Chilli Paneer",
    category: "cat-chinese-gravy",
    categoryId: "cat-chinese-gravy",
    categoryName: "Chinese Gravy",
    description: "Soft paneer cubes simmered in flavourful Indo-Chinese spicy soy-gravy.",
    costPrice: 85,
    sellingPrice: 200,
    price: 200,
    isVeg: true,
    prepTimeMinutes: 11,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cpg-1", name: "Full Gravy Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "cg-2",
    name: "Chilli Mushroom",
    category: "cat-chinese-gravy",
    categoryId: "cat-chinese-gravy",
    categoryName: "Chinese Gravy",
    description: "Fresh button mushrooms tossed in rich garlic and chilli-infused gravy.",
    costPrice: 90,
    sellingPrice: 220,
    price: 220,
    isVeg: true,
    prepTimeMinutes: 11,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cmg-1", name: "Full Gravy Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "cg-3",
    name: "Chicken Manchurian(8Pcs)",
    category: "cat-chinese-gravy",
    categoryId: "cat-chinese-gravy",
    categoryName: "Chinese Gravy",
    description: "Chicken meatballs (8 pcs) simmered in tangy, dark soy coriander gravy.",
    costPrice: 80,
    sellingPrice: 190,
    price: 190,
    isVeg: false,
    prepTimeMinutes: 12,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cm8-1", name: "8 Pcs Gravy Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "cg-4",
    name: "Chilli Chicken (8Pcs)",
    category: "cat-chinese-gravy",
    categoryId: "cat-chinese-gravy",
    categoryName: "Chinese Gravy",
    description: "Classic tender chicken chunks (8 pcs) in rich hot chilli gravy.",
    costPrice: 80,
    sellingPrice: 190,
    price: 190,
    isVeg: false,
    prepTimeMinutes: 12,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cc8-1", name: "8 Pcs Gravy Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "cg-5",
    name: "Schezwa chicken (8Pcs)",
    category: "cat-chinese-gravy",
    categoryId: "cat-chinese-gravy",
    categoryName: "Chinese Gravy",
    description: "Succulent chicken chunks (8 pcs) tossed in fiery Schezwan pepper gravy.",
    costPrice: 85,
    sellingPrice: 200,
    price: 200,
    isVeg: false,
    prepTimeMinutes: 12,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-sc8-1", name: "8 Pcs Gravy Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },

  // ================= 10. INDIAN GRAVY (Page 4) =================
  {
    id: "ig-1",
    name: "Chicken Kosa (4Pcs)",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Authentic Bengali style rich and spicy slow-cooked chicken kasha (4 pcs).",
    costPrice: 65,
    sellingPrice: 150,
    price: 150,
    isVeg: false,
    prepTimeMinutes: 12,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ck4-1", name: "4 Pcs Portion", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "ig-2",
    name: "Chicken Darbari (With Egg) 6Pcs",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Royal aromatic chicken curry (6 pcs) cooked with boiled egg and rich spices.",
    costPrice: 95,
    sellingPrice: 220,
    price: 220,
    isVeg: false,
    prepTimeMinutes: 14,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cd6-1", name: "6 Pcs with Egg", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "ig-3",
    name: "Chicken Butter Masala (4Pcs)",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Tender chicken pieces (4 pcs) in creamy rich tomato-butter-cashew gravy.",
    costPrice: 90,
    sellingPrice: 220,
    price: 220,
    isVeg: false,
    prepTimeMinutes: 14,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cbm4-1", name: "4 Pcs Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "ig-4",
    name: "Chicken Do Pyaza (4Pcs)",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Chicken chunks (4 pcs) simmered with double onions and roasted spices.",
    costPrice: 85,
    sellingPrice: 200,
    price: 200,
    isVeg: false,
    prepTimeMinutes: 13,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cdp4-1", name: "4 Pcs Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "ig-5",
    name: "Chicken Kadai (6Pcs)",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Spicy chicken pieces (6 pcs) tossed with freshly pounded kadai masala and bell peppers.",
    costPrice: 95,
    sellingPrice: 230,
    price: 230,
    isVeg: false,
    prepTimeMinutes: 14,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ck6-1", name: "6 Pcs Kadai Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "ig-6",
    name: "Peটুক আdda Special Chicken(6Pcs)",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "House special rich chicken curry (6 pcs) prepared with chef's secret aromatic gravy.",
    costPrice: 110,
    sellingPrice: 260,
    price: 260,
    isVeg: false,
    prepTimeMinutes: 15,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-pasck6-1", name: "6 Pcs House Special", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "ig-7",
    name: "Panner Butter Masala",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Cottage cheese cubes in velvety tomato makhani gravy enriched with butter and cream.",
    costPrice: 95,
    sellingPrice: 230,
    price: 230,
    isVeg: true,
    prepTimeMinutes: 12,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-pbm-1", name: "Full Gravy Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "ig-8",
    name: "Panner Do Pyaza",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Paneer cubes simmered in spiced onion gravy with caramelized onion petals.",
    costPrice: 85,
    sellingPrice: 210,
    price: 210,
    isVeg: true,
    prepTimeMinutes: 12,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-pdp-1", name: "Full Gravy Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "ig-9",
    name: "Panner Kadai",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Paneer cooked in a traditional wok with capsicum, tomatoes and freshly ground kadai spices.",
    costPrice: 90,
    sellingPrice: 220,
    price: 220,
    isVeg: true,
    prepTimeMinutes: 12,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-pk-1", name: "Full Gravy Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "ig-10",
    name: "Chana Paneer",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Hearty combination of chickpeas and paneer cooked in spiced masala gravy.",
    costPrice: 45,
    sellingPrice: 110,
    price: 110,
    isVeg: true,
    prepTimeMinutes: 10,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cp-g1", name: "Full Gravy Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "ig-11",
    name: "Peটুক আdda Special Paneer",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Chef's signature royal paneer dish prepared in rich saffron-cashew gravy.",
    costPrice: 110,
    sellingPrice: 260,
    price: 260,
    isVeg: true,
    prepTimeMinutes: 14,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-pasp-1", name: "Royal Special Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "ig-12",
    name: "Tadka",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Authentic roadside style tempered dal tadka bursting with aroma.",
    costPrice: 25,
    sellingPrice: 60,
    price: 60,
    isVeg: true,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-tdk-1", name: "1 Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"]
  },
  {
    id: "ig-13",
    name: "Egg Tadka",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Classic tempered dal cooked with scrambled eggs and aromatic spices.",
    costPrice: 30,
    sellingPrice: 70,
    price: 70,
    isVeg: false,
    prepTimeMinutes: 9,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-etdk-1", name: "1 Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1", "add-2"]
  },
  {
    id: "ig-14",
    name: "Chicken Tadka",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "Tempered dal cooked with tender minced chicken chunks.",
    costPrice: 40,
    sellingPrice: 90,
    price: 90,
    isVeg: false,
    prepTimeMinutes: 10,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ctdk-1", name: "1 Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1", "add-3"]
  },
  {
    id: "ig-15",
    name: "Egg Chicken Tadka",
    category: "cat-indian-gravy",
    categoryId: "cat-indian-gravy",
    categoryName: "Indian Gravy",
    description: "The ultimate signature tadka loaded with both scrambled eggs and chicken.",
    costPrice: 45,
    sellingPrice: 100,
    price: 100,
    isVeg: false,
    prepTimeMinutes: 10,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ectdk-1", name: "1 Bowl", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1", "add-3"]
  },

  // ================= 11. ROTI (Page 5) =================
  {
    id: "roti-1",
    name: "Tawa Roti (1 Pcs)",
    category: "cat-roti",
    categoryId: "cat-roti",
    categoryName: "Roti",
    description: "Freshly made whole wheat flatbread on tawa (1 pc).",
    costPrice: 2,
    sellingPrice: 5,
    price: 5,
    isVeg: true,
    prepTimeMinutes: 3,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-tr-1", name: "1 Pc", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "roti-2",
    name: "Butter Tawa Roti (1Pcs)",
    category: "cat-roti",
    categoryId: "cat-roti",
    categoryName: "Roti",
    description: "Soft hot tawa roti brushed with fresh butter (1 pc).",
    costPrice: 3,
    sellingPrice: 7,
    price: 7,
    isVeg: true,
    prepTimeMinutes: 3,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-btr-1", name: "1 Pc", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "roti-3",
    name: "Tawa Paratha (1Pcs)",
    category: "cat-roti",
    categoryId: "cat-roti",
    categoryName: "Roti",
    description: "Flaky layered tawa paratha shallow fried to golden perfection (1 pc).",
    costPrice: 6,
    sellingPrice: 15,
    price: 15,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-tp-1", name: "1 Pc", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "roti-4",
    name: "Butter Tawa Paratha(1Pcs)",
    category: "cat-roti",
    categoryId: "cat-roti",
    categoryName: "Roti",
    description: "Crispy layered tawa paratha topped with butter (1 pc).",
    costPrice: 7,
    sellingPrice: 18,
    price: 18,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-btp-1", name: "1 Pc", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "roti-5",
    name: "Fry Naan (1Pcs)",
    category: "cat-roti",
    categoryId: "cat-roti",
    categoryName: "Roti",
    description: "Crispy and fluffy deep-fried naan bread (1 pc).",
    costPrice: 14,
    sellingPrice: 35,
    price: 35,
    isVeg: true,
    prepTimeMinutes: 5,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-fn-1", name: "1 Pc", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "roti-6",
    name: "Butter Fry naan (1Pcs)",
    category: "cat-roti",
    categoryId: "cat-roti",
    categoryName: "Roti",
    description: "Golden fried naan coated with rich melted butter (1 pc).",
    costPrice: 16,
    sellingPrice: 40,
    price: 40,
    isVeg: true,
    prepTimeMinutes: 5,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-bfn-1", name: "1 Pc", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },

  // ================= 12. RICE (Page 5) =================
  {
    id: "rice-1",
    name: "Veg Fried Rice",
    category: "cat-rice",
    categoryId: "cat-rice",
    categoryName: "Rice",
    description: "Fragrant basmati rice wok-tossed with fresh finely chopped vegetables.",
    costPrice: 45,
    sellingPrice: 120,
    price: 120,
    isVeg: true,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-vfr-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "rice-2",
    name: "Egg Friend Rice",
    category: "cat-rice",
    categoryId: "cat-rice",
    categoryName: "Rice",
    description: "Wok-tossed basmati rice with scrambled egg, spring onions and pepper.",
    costPrice: 50,
    sellingPrice: 130,
    price: 130,
    isVeg: false,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-efr-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-2"]
  },
  {
    id: "rice-3",
    name: "Egg Chicken Fried rice",
    category: "cat-rice",
    categoryId: "cat-rice",
    categoryName: "Rice",
    description: "Aromatic fried rice loaded with tender chicken chunks and scrambled egg.",
    costPrice: 60,
    sellingPrice: 150,
    price: 150,
    isVeg: false,
    prepTimeMinutes: 9,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ecfr-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-3"]
  },
  {
    id: "rice-4",
    name: "Veg Schezwan Rice",
    category: "cat-rice",
    categoryId: "cat-rice",
    categoryName: "Rice",
    description: "Spicy wok-fried rice tossed in zesty red Schezwan sauce and vegetables.",
    costPrice: 50,
    sellingPrice: 130,
    price: 130,
    isVeg: true,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-vsr-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "rice-5",
    name: "Egg Chicken Schezwan rice",
    category: "cat-rice",
    categoryId: "cat-rice",
    categoryName: "Rice",
    description: "Fiery Schezwan fried rice loaded with chicken and egg.",
    costPrice: 65,
    sellingPrice: 160,
    price: 160,
    isVeg: false,
    prepTimeMinutes: 9,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ecsr-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-3"]
  },
  {
    id: "rice-6",
    name: "Jeera Rice",
    category: "cat-rice",
    categoryId: "cat-rice",
    categoryName: "Rice",
    description: "Long grain basmati rice tempered with ghee and aromatic roasted cumin seeds.",
    costPrice: 35,
    sellingPrice: 90,
    price: 90,
    isVeg: true,
    prepTimeMinutes: 6,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-jr-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "rice-7",
    name: "Kamala Rice",
    category: "cat-rice",
    categoryId: "cat-rice",
    categoryName: "Rice",
    description: "Sweet and savoury aromatic spiced orange saffron pulao.",
    costPrice: 55,
    sellingPrice: 140,
    price: 140,
    isVeg: true,
    prepTimeMinutes: 8,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-kr-1", name: "Full Plate", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },

  // ================= 13. MOCKTAIL (Page 5) =================
  {
    id: "mock-1",
    name: "Mint Mojito",
    category: "cat-mocktail",
    categoryId: "cat-mocktail",
    categoryName: "Mocktail",
    description: "Chilled sparkling cooler with fresh mint leaves, lime and crushed ice.",
    costPrice: 25,
    sellingPrice: 70,
    price: 70,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-mm-1", name: "Tall Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "mock-2",
    name: "Virgin Mojito",
    category: "cat-mocktail",
    categoryId: "cat-mocktail",
    categoryName: "Mocktail",
    description: "Classic refreshing blend of fresh lemon, mint sprigs and fizzy soda.",
    costPrice: 25,
    sellingPrice: 70,
    price: 70,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-vm-1", name: "Tall Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "mock-3",
    name: "Blue Lagoon",
    category: "cat-mocktail",
    categoryId: "cat-mocktail",
    categoryName: "Mocktail",
    description: "Vibrant blue curaçao mocktail with zesty citrus notes and fizz.",
    costPrice: 28,
    sellingPrice: 70,
    price: 70,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-bl-1", name: "Tall Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "mock-4",
    name: "Peটুক আdda special Mocktail",
    category: "cat-mocktail",
    categoryId: "cat-mocktail",
    categoryName: "Mocktail",
    description: "House special exotic layered tropical fruit mocktail.",
    costPrice: 32,
    sellingPrice: 80,
    price: 80,
    isVeg: true,
    prepTimeMinutes: 5,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-pasmock-1", name: "Special Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },

  // ================= 14. SHAKE (Page 6) =================
  {
    id: "shk-1",
    name: "Kitkat Shake",
    category: "cat-shake",
    categoryId: "cat-shake",
    categoryName: "Shake",
    description: "Thick creamy shake blended with crunchy KitKat bars and chocolate drizzle.",
    costPrice: 38,
    sellingPrice: 90,
    price: 90,
    isVeg: true,
    prepTimeMinutes: 5,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-ks-1", name: "Standard Shake Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "shk-2",
    name: "Chocolate Shake",
    category: "cat-shake",
    categoryId: "cat-shake",
    categoryName: "Shake",
    description: "Rich and indulgent thick chocolate milkshake.",
    costPrice: 35,
    sellingPrice: 90,
    price: 90,
    isVeg: true,
    prepTimeMinutes: 5,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cs-1", name: "Standard Shake Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "shk-3",
    name: "Juicy Strawberry shake",
    category: "cat-shake",
    categoryId: "cat-shake",
    categoryName: "Shake",
    description: "Thick creamy milkshake made with sweet strawberry compote.",
    costPrice: 40,
    sellingPrice: 99,
    price: 99,
    isVeg: true,
    prepTimeMinutes: 5,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1553787499-6f9133860278?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-jss-1", name: "Standard Shake Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "shk-4",
    name: "Vanila Milk Rose",
    category: "cat-shake",
    categoryId: "cat-shake",
    categoryName: "Shake",
    description: "Fragrant rose syrup infused with chilled creamy vanilla milk.",
    costPrice: 38,
    sellingPrice: 99,
    price: 99,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1553787499-6f9133860278?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-vmr-1", name: "Standard Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },

  // ================= 15. ICE CREAM (Page 6) =================
  {
    id: "ic-1",
    name: "Vanila Ice cream",
    category: "cat-ice-cream",
    categoryId: "cat-ice-cream",
    categoryName: "Ice Cream",
    description: "Classic rich and creamy vanilla bean ice cream scoop.",
    costPrice: 20,
    sellingPrice: 50,
    price: 50,
    isVeg: true,
    prepTimeMinutes: 2,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-vic-1", name: "1 Scoop", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "ic-2",
    name: "Chocolate Ice Cream",
    category: "cat-ice-cream",
    categoryId: "cat-ice-cream",
    categoryName: "Ice Cream",
    description: "Decadent dark chocolate ice cream scoop.",
    costPrice: 25,
    sellingPrice: 65,
    price: 65,
    isVeg: true,
    prepTimeMinutes: 2,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-cic-1", name: "1 Scoop", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "ic-3",
    name: "Butter Scotch Ice Cream",
    category: "cat-ice-cream",
    categoryId: "cat-ice-cream",
    categoryName: "Ice Cream",
    description: "Crunchy butterscotch praline blended in creamy caramel ice cream.",
    costPrice: 25,
    sellingPrice: 60,
    price: 60,
    isVeg: true,
    prepTimeMinutes: 2,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-bsic-1", name: "1 Scoop", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },

  // ================= 16. LASSI (Page 6) =================
  {
    id: "las-1",
    name: "Lassi",
    category: "cat-lassi",
    categoryId: "cat-lassi",
    categoryName: "Lassi",
    description: "Traditional sweet thick Punjabi curd lassi.",
    costPrice: 18,
    sellingPrice: 40,
    price: 40,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1553787499-6f9133860278?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-las-1", name: "1 Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "las-2",
    name: "Special Lassi",
    category: "cat-lassi",
    categoryId: "cat-lassi",
    categoryName: "Lassi",
    description: "Rich creamy lassi garnished with dry fruits, saffron and malai.",
    costPrice: 25,
    sellingPrice: 60,
    price: 60,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1553787499-6f9133860278?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-slas-1", name: "1 Special Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },
  {
    id: "las-3",
    name: "Chas",
    category: "cat-lassi",
    categoryId: "cat-lassi",
    categoryName: "Lassi",
    description: "Cool and refreshing salted buttermilk spiced with roasted cumin and mint.",
    costPrice: 12,
    sellingPrice: 30,
    price: 30,
    isVeg: true,
    prepTimeMinutes: 3,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1553787499-6f9133860278?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-chas-1", name: "1 Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: []
  },

  // ================= 17. COFFEE (Production hardening pack, Rs 99-349) =================
  {
    id: "qa-cof-1",
    name: "Classic Cappuccino",
    category: "cat-coffee",
    categoryId: "cat-coffee",
    categoryName: "Coffee",
    description: "Double espresso with steamed milk and a thick cappuccino foam cap.",
    costPrice: 55,
    sellingPrice: 149,
    price: 149,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1534778101976-62847782c213?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-qacof1-1", name: "Regular", priceDelta: 0, isDefault: true }],
    allowedAddons: [],
    inventoryIngredients: [
      { ingredientId: "inv-1", quantity: 0.018 },
      { ingredientId: "inv-2", quantity: 0.15 }
    ]
  },
  {
    id: "qa-cof-2",
    name: "Cafe Latte",
    category: "cat-coffee",
    categoryId: "cat-coffee",
    categoryName: "Coffee",
    description: "Smooth double shot latte with silky steamed milk.",
    costPrice: 60,
    sellingPrice: 169,
    price: 169,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-qacof2-1", name: "Regular", priceDelta: 0, isDefault: true }],
    allowedAddons: [],
    inventoryIngredients: [
      { ingredientId: "inv-1", quantity: 0.018 },
      { ingredientId: "inv-2", quantity: 0.2 }
    ]
  },
  {
    id: "qa-cof-3",
    name: "Espresso Double Shot",
    category: "cat-coffee",
    categoryId: "cat-coffee",
    categoryName: "Coffee",
    description: "Intense double ristretto shot from single-origin arabica beans.",
    costPrice: 35,
    sellingPrice: 99,
    price: 99,
    isVeg: true,
    prepTimeMinutes: 2,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-qacof3-1", name: "Double Shot", priceDelta: 0, isDefault: true }],
    allowedAddons: [],
    inventoryIngredients: [{ ingredientId: "inv-1", quantity: 0.018 }]
  },

  // ================= 18. COLD BREWS (Production hardening pack, Rs 99-349) =================
  {
    id: "qa-cb-1",
    name: "Classic Cold Brew",
    category: "cat-cold-brews",
    categoryId: "cat-cold-brews",
    categoryName: "Cold Brews",
    description: "18-hour slow-steeped cold brew served over ice.",
    costPrice: 70,
    sellingPrice: 199,
    price: 199,
    isVeg: true,
    prepTimeMinutes: 3,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-qacb1-1", name: "Tall Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: [],
    inventoryIngredients: [
      { ingredientId: "inv-1", quantity: 0.03 },
      { ingredientId: "inv-6", quantity: 0.01 }
    ]
  },
  {
    id: "qa-cb-2",
    name: "Nitro Cold Brew",
    category: "cat-cold-brews",
    categoryId: "cat-cold-brews",
    categoryName: "Cold Brews",
    description: "Nitrogen-infused cascading cold brew with a creamy head.",
    costPrice: 85,
    sellingPrice: 249,
    price: 249,
    isVeg: true,
    prepTimeMinutes: 3,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-qacb2-1", name: "Nitro Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: [],
    inventoryIngredients: [{ ingredientId: "inv-1", quantity: 0.035 }]
  },
  {
    id: "qa-cb-3",
    name: "Vietnamese Iced Coffee",
    category: "cat-cold-brews",
    categoryId: "cat-cold-brews",
    categoryName: "Cold Brews",
    description: "Bold cold brew with condensed milk over crushed ice.",
    costPrice: 65,
    sellingPrice: 199,
    price: 199,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1517959105821-eaf2591984ca?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-qacb3-1", name: "Tall Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: [],
    inventoryIngredients: [
      { ingredientId: "inv-1", quantity: 0.03 },
      { ingredientId: "inv-2", quantity: 0.05 }
    ]
  },

  // ================= 19. TEAS (Production hardening pack, Rs 99-349) =================
  {
    id: "qa-tea-1",
    name: "Masala Chai Kulhad",
    category: "cat-teas",
    categoryId: "cat-teas",
    categoryName: "Teas",
    description: "Slow-brewed spiced masala chai served piping hot in a kulhad.",
    costPrice: 30,
    sellingPrice: 99,
    price: 99,
    isVeg: true,
    prepTimeMinutes: 5,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-qatea1-1", name: "Kulhad", priceDelta: 0, isDefault: true }],
    allowedAddons: [],
    inventoryIngredients: [
      { ingredientId: "inv-7", quantity: 0.008 },
      { ingredientId: "inv-2", quantity: 0.12 }
    ]
  },
  {
    id: "qa-tea-2",
    name: "Earl Grey Tea",
    category: "cat-teas",
    categoryId: "cat-teas",
    categoryName: "Teas",
    description: "Fragrant earl grey with bergamot, served with honey on the side.",
    costPrice: 45,
    sellingPrice: 149,
    price: 149,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-qatea2-1", name: "Pot", priceDelta: 0, isDefault: true }],
    allowedAddons: [],
    inventoryIngredients: [
      { ingredientId: "inv-7", quantity: 0.01 },
      { ingredientId: "inv-6", quantity: 0.01 }
    ]
  },
  {
    id: "qa-tea-3",
    name: "Iced Peach Tea",
    category: "cat-teas",
    categoryId: "cat-teas",
    categoryName: "Teas",
    description: "Chilled black tea with peach and mint over ice.",
    costPrice: 50,
    sellingPrice: 179,
    price: 179,
    isVeg: true,
    prepTimeMinutes: 4,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-qatea3-1", name: "Tall Glass", priceDelta: 0, isDefault: true }],
    allowedAddons: [],
    inventoryIngredients: [
      { ingredientId: "inv-7", quantity: 0.01 },
      { ingredientId: "inv-6", quantity: 0.015 }
    ]
  },

  // ================= 20. BAKERY (Production hardening pack, Rs 99-349) =================
  {
    id: "qa-bak-1",
    name: "Butter Croissant",
    category: "cat-bakery",
    categoryId: "cat-bakery",
    categoryName: "Bakery",
    description: "Flaky French butter croissant baked fresh every morning.",
    costPrice: 45,
    sellingPrice: 129,
    price: 129,
    isVeg: true,
    prepTimeMinutes: 3,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-qabak1-1", name: "1 Pc", priceDelta: 0, isDefault: true }],
    allowedAddons: ["add-1"],
    inventoryIngredients: [
      { ingredientId: "inv-9", quantity: 1 },
      { ingredientId: "inv-10", quantity: 0.02 }
    ]
  },
  {
    id: "qa-bak-2",
    name: "Choco Chip Muffin",
    category: "cat-bakery",
    categoryId: "cat-bakery",
    categoryName: "Bakery",
    description: "Moist chocolate-chip muffin with a molten centre.",
    costPrice: 40,
    sellingPrice: 119,
    price: 119,
    isVeg: true,
    prepTimeMinutes: 3,
    isAvailable: true,
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-qabak2-1", name: "1 Pc", priceDelta: 0, isDefault: true }],
    allowedAddons: [],
    inventoryIngredients: [
      { ingredientId: "inv-5", quantity: 0.02 },
      { ingredientId: "inv-6", quantity: 0.03 }
    ]
  },
  {
    id: "qa-bak-3",
    name: "Blueberry Cheesecake Slice",
    category: "cat-bakery",
    categoryId: "cat-bakery",
    categoryName: "Bakery",
    description: "Baked New York cheesecake slice with blueberry compote.",
    costPrice: 120,
    sellingPrice: 349,
    price: 349,
    isVeg: true,
    prepTimeMinutes: 3,
    isAvailable: true,
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=500&auto=format&fit=crop&q=60",
    variants: [{ id: "var-qabak3-1", name: "1 Slice", priceDelta: 0, isDefault: true }],
    allowedAddons: [],
    inventoryIngredients: [
      { ingredientId: "inv-8", quantity: 0.08 },
      { ingredientId: "inv-6", quantity: 0.02 }
    ]
  }
];

export const initialBranches = [
  {
    id: "br-main",
    name: "Petuk Adda — Flagship Store",
    code: "FLAGSHIP",
    address: "Salboni, Sakadihi-Ailakundi Road, Near Salboni High School, Salboni, West Bengal 722102",
    phone: "+91 9932148058",
    email: "petukaddacafe@gmail.com",
    managerName: "Ananya Iyer",
    openingHours: "09:00 AM – 10:30 PM (Open All Days)",
    isActive: true
  },
  {
    id: "br-riverside",
    name: "Petuk Adda — Riverside",
    code: "RIVERSIDE",
    address: "River View Road, Near Kangsabati Bridge, Bankura, West Bengal 722101",
    phone: "+91 6292314286",
    email: "riverside@petukaddacafe.com",
    managerName: "David Chen",
    openingHours: "10:00 AM – 10:00 PM (Open All Days)",
    isActive: true
  }
];

export const initialTables = [
  { id: "tbl-1", tableNumber: "T-01", zone: "Indoor Cafe", capacity: 2, status: "Occupied", currentOrderId: "ord-101", customerName: "Arjun Das", x: 1, y: 1 },
  { id: "tbl-2", tableNumber: "T-02", zone: "Indoor Cafe", capacity: 4, status: "Available", currentOrderId: null, customerName: null, x: 2, y: 1 },
  { id: "tbl-3", tableNumber: "T-03", zone: "Indoor Cafe", capacity: 4, status: "Reserved", currentOrderId: null, customerName: "Sita Patel", x: 3, y: 1 },
  { id: "tbl-4", tableNumber: "T-04", zone: "Indoor Cafe", capacity: 6, status: "Available", currentOrderId: null, customerName: null, x: 4, y: 1 },
  { id: "tbl-5", tableNumber: "T-05", zone: "Garden Terrace", capacity: 2, status: "Available", currentOrderId: null, customerName: null, x: 1, y: 2 },
  { id: "tbl-6", tableNumber: "T-06", zone: "Garden Terrace", capacity: 4, status: "Occupied", currentOrderId: "ord-102", customerName: "Meera Sen", x: 2, y: 2 },
  { id: "tbl-7", tableNumber: "T-07", zone: "Garden Terrace", capacity: 4, status: "Cleaning", currentOrderId: null, customerName: null, x: 3, y: 2 },
  { id: "tbl-8", tableNumber: "T-08", zone: "Garden Terrace", capacity: 8, status: "Available", currentOrderId: null, customerName: null, x: 4, y: 2 }
];

export const initialCustomers = [
  {
    id: "cust-5",
    name: "Siddharth Sen",
    phone: "+91 99001 88990",
    email: "sid.sen@example.com",
    tier: "Bronze",
    loyaltyPoints: 15,
    totalSpent: 650,
    totalOrders: 1,
    lastVisit: "2026-09-01T14:10:00Z",
    favoriteProducts: ["Single-Origin Americano"],
    notes: "First order via POS takeaway."
  }
];

export const initialCoupons = [
  {
    id: "cpn-1",
    code: "WELCOME50",
    name: "New Guest Special",
    description: "50% instant discount up to ₹150 for new coffee lovers.",
    discountType: "percentage",
    discountValue: 50,
    maxDiscount: 150,
    minOrderValue: 299,
    maxOrderValue: null,
    startDate: "2026-01-01",
    expiryDate: "2026-12-31",
    usageLimit: 500,
    usedCount: 142,
    perCustomerLimit: 1,
    status: "active",
    applicableCategories: [],
    applicableOrderTypes: ["dine-in", "takeaway", "delivery"],
    customerEligibility: "new",
    totalDiscountGiven: 17750,
    revenueGenerated: 64200
  },
  {
    id: "cpn-2",
    code: "PETUK20",
    name: "Petuk Adda 20% Welcome",
    description: "20% flat discount on all handcrafted specialty coffees & gourmet dining.",
    discountType: "percentage",
    discountValue: 20,
    maxDiscount: 200,
    minOrderValue: 400,
    maxOrderValue: null,
    startDate: "2026-08-01",
    expiryDate: "2026-09-30",
    usageLimit: 300,
    usedCount: 88,
    perCustomerLimit: 3,
    status: "active",
    applicableCategories: [],
    applicableOrderTypes: ["dine-in", "takeaway", "delivery"],
    customerEligibility: "all",
    totalDiscountGiven: 12320,
    revenueGenerated: 61600
  },
  {
    id: "cpn-3",
    code: "COFFEE50",
    name: "Flat ₹50 Coffee Treat",
    description: "Instant ₹50 deduction on minimum order value of ₹250.",
    discountType: "fixed",
    discountValue: 50,
    maxDiscount: 50,
    minOrderValue: 250,
    maxOrderValue: null,
    startDate: "2026-08-15",
    expiryDate: "2026-09-15",
    usageLimit: 200,
    usedCount: 65,
    perCustomerLimit: 2,
    status: "active",
    applicableCategories: ["cat-1", "cat-2"],
    applicableOrderTypes: ["dine-in", "takeaway"],
    customerEligibility: "all",
    totalDiscountGiven: 3250,
    revenueGenerated: 21450
  },
  {
    id: "cpn-4",
    code: "SUMMER99",
    name: "Summer Cold Brew Fest",
    description: "Special seasonal promotion expired last month.",
    discountType: "fixed",
    discountValue: 99,
    maxDiscount: 99,
    minOrderValue: 350,
    maxOrderValue: null,
    startDate: "2026-06-01",
    expiryDate: "2026-08-01",
    usageLimit: 100,
    usedCount: 100,
    perCustomerLimit: 1,
    status: "expired",
    applicableCategories: ["cat-2"],
    applicableOrderTypes: ["dine-in", "takeaway"],
    customerEligibility: "all",
    totalDiscountGiven: 9900,
    revenueGenerated: 42000
  },
  // ---- Production hardening pack: mission-required coupons (idempotent) ----
  {
    id: "cpn-welcome10",
    code: "WELCOME10",
    name: "Welcome 10% Off",
    description: "10% instant discount up to ₹100 for all guests.",
    discountType: "percentage",
    discountValue: 10,
    maxDiscount: 100,
    minOrderValue: 199,
    maxOrderValue: null,
    startDate: "2026-01-01",
    expiryDate: "2026-12-31",
    usageLimit: 1000,
    usedCount: 0,
    perCustomerLimit: 1,
    status: "active",
    applicableCategories: [],
    applicableOrderTypes: ["dine-in", "takeaway", "delivery"],
    customerEligibility: "all",
    totalDiscountGiven: 0,
    revenueGenerated: 0
  },
  {
    id: "cpn-flat50",
    code: "FLAT50",
    name: "Flat ₹50 Off",
    description: "Instant ₹50 deduction on minimum order value of ₹249.",
    discountType: "fixed",
    discountValue: 50,
    maxDiscount: 50,
    minOrderValue: 249,
    maxOrderValue: null,
    startDate: "2026-01-01",
    expiryDate: "2026-12-31",
    usageLimit: 1000,
    usedCount: 0,
    perCustomerLimit: 2,
    status: "active",
    applicableCategories: [],
    applicableOrderTypes: ["dine-in", "takeaway", "delivery"],
    customerEligibility: "all",
    totalDiscountGiven: 0,
    revenueGenerated: 0
  },
  {
    id: "cpn-loyal15",
    code: "LOYAL15",
    name: "Loyal Guests 15% Off",
    description: "15% loyalty discount up to ₹150 on orders above ₹499.",
    discountType: "percentage",
    discountValue: 15,
    maxDiscount: 150,
    minOrderValue: 499,
    maxOrderValue: null,
    startDate: "2026-01-01",
    expiryDate: "2026-12-31",
    usageLimit: 1000,
    usedCount: 0,
    perCustomerLimit: 3,
    status: "active",
    applicableCategories: [],
    applicableOrderTypes: ["dine-in", "takeaway", "delivery"],
    customerEligibility: "all",
    totalDiscountGiven: 0,
    revenueGenerated: 0
  }
];

export const initialInventory = [
  { id: "inv-1", name: "Arabica Coffee Beans (Single Origin)", category: "Raw Material", unit: "KG", currentStock: 8.5, minStock: 5.0, maxStock: 25.0, costPerUnit: 1200, supplierId: "sup-1", expiryDate: "2027-03-15", status: "In Stock" },
  { id: "inv-2", name: "Fresh Full Cream Milk", category: "Dairy", unit: "Litre", currentStock: 3.2, minStock: 10.0, maxStock: 40.0, costPerUnit: 68, supplierId: "sup-2", expiryDate: "2026-09-04", status: "Low Stock" },
  { id: "inv-3", name: "Organic Oat Milk", category: "Dairy Alternative", unit: "Litre", currentStock: 12.0, minStock: 5.0, maxStock: 20.0, costPerUnit: 180, supplierId: "sup-2", expiryDate: "2026-11-20", status: "In Stock" },
  { id: "inv-4", name: "Almond Barista Milk", category: "Dairy Alternative", unit: "Litre", currentStock: 6.5, minStock: 4.0, maxStock: 15.0, costPerUnit: 195, supplierId: "sup-2", expiryDate: "2026-11-15", status: "In Stock" },
  { id: "inv-5", name: "Valrhona Dark Cocoa Powder", category: "Dry Goods", unit: "KG", currentStock: 3.0, minStock: 2.0, maxStock: 10.0, costPerUnit: 1450, supplierId: "sup-1", expiryDate: "2027-06-30", status: "In Stock" },
  { id: "inv-6", name: "Organic Cane Sugar", category: "Sweeteners", unit: "KG", currentStock: 18.0, minStock: 8.0, maxStock: 50.0, costPerUnit: 52, supplierId: "sup-3", expiryDate: "2027-09-01", status: "In Stock" },
  { id: "inv-7", name: "Earl Grey Tea Leaves", category: "Raw Material", unit: "KG", currentStock: 2.1, minStock: 1.5, maxStock: 8.0, costPerUnit: 1800, supplierId: "sup-1", expiryDate: "2027-05-10", status: "In Stock" },
  { id: "inv-8", name: "Mozzarella & Cheddar Cheese Blend", category: "Dairy", unit: "KG", currentStock: 4.8, minStock: 4.0, maxStock: 15.0, costPerUnit: 480, supplierId: "sup-2", expiryDate: "2026-09-25", status: "In Stock" },
  { id: "inv-9", name: "Artisan Sourdough Bread Loaves", category: "Bakery", unit: "Loaf", currentStock: 2.0, minStock: 5.0, maxStock: 20.0, costPerUnit: 120, supplierId: "sup-3", expiryDate: "2026-09-03", status: "Low Stock" },
  { id: "inv-10", name: "French Unsalted Butter", category: "Dairy", unit: "KG", currentStock: 5.5, minStock: 3.0, maxStock: 15.0, costPerUnit: 620, supplierId: "sup-2", expiryDate: "2026-10-15", status: "In Stock" },
  { id: "inv-11", name: "Neapolitan Pizza Dough Balls", category: "Bakery", unit: "PCS", currentStock: 18.0, minStock: 10.0, maxStock: 50.0, costPerUnit: 45, supplierId: "sup-3", expiryDate: "2026-09-05", status: "In Stock" },
  { id: "inv-12", name: "Eco Kraft Takeaway Cups (350ml)", category: "Packaging", unit: "PCS", currentStock: 380, minStock: 150, maxStock: 1000, costPerUnit: 6.5, supplierId: "sup-4", expiryDate: "2029-01-01", status: "In Stock" }
];

export const initialSuppliers = [
  { id: "sup-1", name: "Origin Coffee & Tea Imports", contactPerson: "Marco Bianchi", phone: "+91 98200 44556", email: "orders@originimports.com", address: "Dockland Estate, Warehouse 4B, Mumbai", category: "Coffee, Tea & Cocoa", paymentTerms: "Net 15 Days", totalPurchases: 145000, status: "Active" },
  { id: "sup-2", name: "Highland Dairy Farms Co.", contactPerson: "Anita Deshmukh", phone: "+91 98400 66778", email: "sales@highlanddairy.in", address: "Farm Route 7, Pune Outskirts", category: "Fresh Milk, Cheese & Butter", paymentTerms: "Weekly on Monday", totalPurchases: 82400, status: "Active" },
  { id: "sup-3", name: "Artisan Bakers Supply Co.", contactPerson: "Kavita Rao", phone: "+91 99000 88991", email: "kavita@artisanbakers.com", address: "Industrial Zone 2, Bengaluru", category: "Sourdough, Dough & Flours", paymentTerms: "Cash on Delivery", totalPurchases: 49500, status: "Active" },
  { id: "sup-4", name: "EcoPack Sustainable Packaging", contactPerson: "Sanjay Verma", phone: "+91 98111 22334", email: "info@ecopack.co", address: "Packaging Hub, Sector 18, Gurugram", category: "Bio Cups, Straws, Boxes", paymentTerms: "Net 30 Days", totalPurchases: 31200, status: "Active" }
];

export const initialPurchases = [
  {
    id: "po-101",
    poNumber: "PO-2026-089",
    supplierId: "sup-1",
    supplierName: "Origin Coffee & Tea Imports",
    orderDate: "2026-08-25",
    receivedDate: "2026-08-27",
    totalAmount: 24000,
    paymentStatus: "Paid",
    status: "Completed",
    notes: "20 KG Arabica beans delivered in pristine condition.",
    items: [{ ingredientId: "inv-1", name: "Arabica Coffee Beans", quantity: 20, unitCost: 1200, totalCost: 24000 }]
  },
  {
    id: "po-102",
    poNumber: "PO-2026-092",
    supplierId: "sup-2",
    supplierName: "Highland Dairy Farms Co.",
    orderDate: "2026-08-30",
    receivedDate: "2026-08-31",
    totalAmount: 6800,
    paymentStatus: "Paid",
    status: "Completed",
    notes: "Fresh weekly milk and cheese batch.",
    items: [
      { ingredientId: "inv-2", name: "Fresh Full Cream Milk", quantity: 50, unitCost: 68, totalCost: 3400 },
      { ingredientId: "inv-8", name: "Cheese Blend", quantity: 7.08, unitCost: 480, totalCost: 3400 }
    ]
  }
];

export const initialExpenses = [
  { id: "exp-1", title: "Cafe Monthly Rent - Ground Floor", category: "Rent", amount: 45000, date: "2026-09-01", paymentMethod: "Online Bank Transfer", referenceNo: "NEFT-89320184", notes: "Monthly property rent paid to landlord.", loggedBy: "Alex Walker (Admin)" },
  { id: "exp-2", title: "Commercial Electricity Bill - August", category: "Electricity", amount: 8420, date: "2026-09-01", paymentMethod: "UPI", referenceNo: "UPI-481920391", notes: "Grid power consumption for roaster and AC units.", loggedBy: "Alex Walker (Admin)" },
  { id: "exp-3", title: "Barista & Kitchen Staff Salaries", category: "Salary", amount: 62000, date: "2026-08-31", paymentMethod: "Online Bank Transfer", referenceNo: "SAL-AUG-2026", notes: "August payroll for 5 team members.", loggedBy: "Alex Walker (Admin)" },
  { id: "exp-4", title: "Espresso Machine Maintenance & Descaling", category: "Maintenance", amount: 3500, date: "2026-08-28", paymentMethod: "Card", referenceNo: "POS-SERV-1092", notes: "La Marzocco group head gasket replacement and water filter check.", loggedBy: "Samantha Reed (Manager)" },
  { id: "exp-5", title: "Instagram Local Ads Campaign", category: "Marketing", amount: 2500, date: "2026-08-25", paymentMethod: "Card", referenceNo: "META-ADS-9021", notes: "Targeted Brisbane CBD coffee enthusiasts.", loggedBy: "Samantha Reed (Manager)" }
];

export const initialStaff = [
  { id: "staff-1", name: "Alex Walker", email: "admin@dinenos.com", phone: "+61 400 111 222", role: "Admin", status: "Active", joiningDate: "2022-01-15", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80" },
  { id: "staff-2", name: "Samantha Reed", email: "manager@dinenos.com", phone: "+61 400 222 333", role: "Manager", status: "Active", joiningDate: "2023-03-01", avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80" },
  { id: "staff-3", name: "David Chen", email: "cashier@dinenos.com", phone: "+61 400 333 444", role: "Cashier", status: "Active", joiningDate: "2024-02-10", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80" },
  { id: "staff-4", name: "Gordon Marco", email: "kitchen@dinenos.com", phone: "+61 400 444 555", role: "Kitchen Staff", status: "Active", joiningDate: "2023-06-20", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80" },
  { id: "staff-5", name: "Elena Silva", email: "waiter@dinenos.com", phone: "+61 400 555 666", role: "Waiter", status: "Active", joiningDate: "2024-05-12", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80" }
];

export const initialReservations = [
  { id: "res-1", customerName: "Sita Patel", phone: "+91 98888 77665", email: "sita.patel@example.com", date: "2026-09-01", time: "18:00", guests: 4, tableId: "tbl-3", tableNumber: "T-03", status: "Confirmed", specialRequest: "Window side birthday setup with extra napkins.", createdAt: "2026-09-01T10:12:00Z" },
  { id: "res-2", customerName: "Marcus Thorne", phone: "+61 422 998 877", email: "marcus@thorne.com", date: "2026-09-01", time: "19:30", guests: 6, tableId: "tbl-4", tableNumber: "T-04", status: "Pending", specialRequest: "Quiet booth for business discussion.", createdAt: "2026-09-01T12:45:00Z" },
  { id: "res-3", customerName: "Clara Oswald", phone: "+61 433 112 244", email: "clara@oswald.com", date: "2026-09-02", time: "11:00", guests: 2, tableId: "tbl-5", tableNumber: "T-05", status: "Confirmed", specialRequest: "Outdoor terrace table.", createdAt: "2026-09-01T14:20:00Z" }
];

export const initialOrders = [
  {
    id: "ord-101",
    orderNumber: "DIN-8021",
    orderType: "dine-in",
    tableNumber: "T-01",
    tableId: "tbl-1",
    customerId: "cust-101",
    customerName: "Arjun Das",
    customerPhone: "+91 98000 11223",
    status: "Preparing", // New, Accepted, Preparing, Ready, Completed, Cancelled, Refunded
    orderTime: "2026-09-01T16:35:00Z",
    kitchenAcceptedAt: "2026-09-01T16:36:00Z",
    kitchenReadyAt: null,
    completedAt: null,
    items: [
      {
        id: "item-101-1",
        productId: "prod-1",
        name: "Classic Latte",
        variant: "Large (350ml)",
        variantPriceDelta: 40,
        unitPrice: 220,
        quantity: 2,
        addons: [{ id: "add-2", name: "Oat Milk Upgrade", price: 50 }],
        notes: "Extra hot with cinnamon dust on top",
        totalPrice: 540
      },
      {
        id: "item-101-2",
        productId: "prod-9",
        name: "Avocado Sourdough Toast",
        variant: "Standard",
        variantPriceDelta: 0,
        unitPrice: 320,
        quantity: 1,
        addons: [{ id: "add-6", name: "Extra Cheddar Cheese", price: 45 }],
        notes: "Well toasted sourdough",
        totalPrice: 365
      }
    ],
    subtotal: 905,
    discountAmount: 150,
    couponCode: "WELCOME50",
    couponId: "cpn-1",
    taxAmount: 37.75, // 5% on discounted subtotal (755 * 0.05)
    serviceCharge: 18.88,
    grandTotal: 811.63,
    paymentMethod: "UPI",
    paymentStatus: "Paid",
    notes: "Customer is dining in at table T-01.",
    serverStaff: "David Chen"
  },
  {
    id: "ord-102",
    orderNumber: "DIN-8022",
    orderType: "dine-in",
    tableNumber: "T-06",
    tableId: "tbl-6",
    customerId: "cust-102",
    customerName: "Meera Sen",
    customerPhone: "+91 98000 33445",
    status: "Accepted",
    orderTime: "2026-09-01T16:48:00Z",
    kitchenAcceptedAt: "2026-09-01T16:49:00Z",
    kitchenReadyAt: null,
    completedAt: null,
    items: [
      {
        id: "item-102-1",
        productId: "prod-2",
        name: "Cappuccino Italiano",
        variant: "Regular",
        variantPriceDelta: 0,
        unitPrice: 190,
        quantity: 1,
        addons: [],
        notes: "No sugar",
        totalPrice: 190
      },
      {
        id: "item-102-2",
        productId: "prod-11",
        name: "Truffle Mushroom Artisan Pizza",
        variant: "Medium 10 inch",
        variantPriceDelta: 0,
        unitPrice: 460,
        quantity: 1,
        addons: [],
        notes: "Crispy crust",
        totalPrice: 460
      }
    ],
    subtotal: 650,
    discountAmount: 0,
    couponCode: null,
    couponId: null,
    taxAmount: 32.50,
    serviceCharge: 16.25,
    grandTotal: 698.75,
    paymentMethod: "Card",
    paymentStatus: "Pending",
    notes: "Garden Terrace seating.",
    serverStaff: "Elena Silva"
  },
  {
    id: "ord-100",
    orderNumber: "DIN-8020",
    orderType: "takeaway",
    tableNumber: null,
    tableId: null,
    customerId: "cust-100",
    customerName: "Rohan Roy",
    customerPhone: "+91 98000 55667",
    status: "Completed",
    orderTime: "2026-09-01T15:10:00Z",
    kitchenAcceptedAt: "2026-09-01T15:11:00Z",
    kitchenReadyAt: "2026-09-01T15:22:00Z",
    completedAt: "2026-09-01T15:25:00Z",
    items: [
      {
        id: "item-100-1",
        productId: "prod-5",
        name: "Nitro Cold Brew",
        variant: "Large (450ml)",
        variantPriceDelta: 50,
        unitPrice: 270,
        quantity: 1,
        addons: [{ id: "add-4", name: "Vanilla / Caramel Syrup", price: 35 }],
        notes: "Packed for commute",
        totalPrice: 305
      },
      {
        id: "item-100-2",
        productId: "prod-10",
        name: "Smoked Chicken Ciabatta",
        variant: "Standard Sandwich",
        variantPriceDelta: 0,
        unitPrice: 340,
        quantity: 1,
        addons: [],
        notes: "",
        totalPrice: 340
      }
    ],
    subtotal: 645,
    discountAmount: 50,
    couponCode: "COFFEE50",
    couponId: "cpn-3",
    taxAmount: 29.75,
    serviceCharge: 0,
    grandTotal: 624.75,
    paymentMethod: "UPI",
    paymentStatus: "Paid",
    notes: "Takeaway order picked up.",
    serverStaff: "David Chen"
  }
];

export const initialAuditLogs = [
  { id: "log-1", timestamp: "2026-09-01T16:35:10Z", user: "David Chen (Cashier)", action: "CREATE_ORDER", category: "Orders", details: "Created Dine-in order #DIN-8021 for Arjun Das at Table T-01 ($811.63)", ip: "192.168.1.45" },
  { id: "log-2", timestamp: "2026-09-01T16:35:05Z", user: "David Chen (Cashier)", action: "APPLY_COUPON", category: "Coupons", details: "Validated and applied coupon WELCOME50 (₹150 discount) for order #DIN-8021", ip: "192.168.1.45" },
  { id: "log-3", timestamp: "2026-09-01T15:25:00Z", user: "David Chen (Cashier)", action: "COMPLETE_ORDER", category: "Orders", details: "Marked order #DIN-8020 as Completed and deducted stock for Nitro Cold Brew & Ciabatta", ip: "192.168.1.45" },
  { id: "log-4", timestamp: "2026-09-01T14:30:22Z", user: "Alex Walker (Admin)", action: "UPDATE_INVENTORY", category: "Inventory", details: "Adjusted Fresh Milk stock +10.0 L (Supplier shipment received)", ip: "192.168.1.10" },
  { id: "log-5", timestamp: "2026-09-01T11:00:15Z", user: "Alex Walker (Admin)", action: "USER_LOGIN", category: "Auth", details: "Admin logged into Cafe Management Portal", ip: "192.168.1.10" }
];

export const initialNotifications = [
  { id: "notif-1", title: "Low Stock Alert", message: "Fresh Full Cream Milk is at 3.2 L (Below minimum 10.0 L threshold).", type: "warning", time: "10 mins ago", isRead: false, link: "/inventory" },
  { id: "notif-2", title: "New Dine-in Order", message: "Order #DIN-8022 placed for Table T-06 (Meera Sen).", type: "order", time: "15 mins ago", isRead: false, link: "/kitchen" },
  { id: "notif-3", title: "Upcoming Reservation", message: "Sita Patel reserved Table T-03 for 4 guests at 6:00 PM today.", type: "reservation", time: "1 hour ago", isRead: true, link: "/reservations" },
  { id: "notif-4", title: "Purchase Order Received", message: "PO-2026-092 from Highland Dairy Farms marked as received.", type: "inventory", time: "3 hours ago", isRead: true, link: "/purchases" }
];
